Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: example-dynamodb-table
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cftail-test-bucket

Outputs:
  TestExport:
    Value: 10
